name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: make package
      - run: cp /tmp/bettywhitelist.tar.gz /tmp/bettywhitelist-${{ github.ref_name }}.tar.gz
      - run: make changelog > /tmp/changelog.txt
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} 
          files: /tmp/bettywhitelist-${{ github.ref_name }}.tar.gz
          body_path: /tmp/changelog.txt
